### ISSUE TITLE
depthwise layer를 사용하는 게 맞나요?

### ISSUE THREAD

**Issue by resurgo97** [upskyy/ContextNet#3]
코드를 돌려보지는 않았지만 내부의 1d conv layer가 depthwise 레이어인 것으로 아는데,
그렇다면 in_channels = out_channnels = groups가 되야 하는 것 아닌가요?

**Comment by upskyy** [comment]
어느 쪽 코드 말씀하시는 걸까요?

**Comment by upskyy** [comment]
이슈 close 하겠습니다.
